- hosts: localhost
  gather_facts: no
  tasks:

   - name: Install provisioning dependencies
     apt: name=python-lxc

   - name: Create four lxc containers on this PC  
     lxc_container:
      name: "{{item.name}}"
      container_log: true
      template: download 
      template_options: --dist centos --release 7 --arch amd64
      state: started
     with_items:
              - { name: 'CentOS7v1' }
              - { name: 'CentOS7v2' }
              - { name: 'CentOS7v3' }
              - { name: 'CentOS7v4' }
#   - import_tasks: apache_install.yml             
