- hosts: localhost
  tasks:

   - name: Install provisioning dependencies
     apt: name=python-lxc

   - name: Remove four lxc containers on this PC  
     lxc_container:
      name: "{{item.name}}"
      container_log: true
      state: absent
     with_items:
              - { name: 'CentOS7v1' }
              - { name: 'CentOS7v2' }
              - { name: 'CentOS7v3' }
              - { name: 'CentOS7v4' }
