---
- hosts: readynas
  remote_user: root
  gather_facts: False
  pre_tasks:
          - name: Install python2 for Ansible
            raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-pip)"
            register: output
            changed_when: output.stdout != ""
  tasks:
          - name: powering off readynas devices
            command: systemctl poweroff
